config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/recommend', to: 'recommended_menus#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :dishes, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_menu_times, only: :home
  before_action :set_dish_categories, only: :home
  before_action :prepare_menu_form, only: :home
  append_after_action :delete_menu_sessions, only: :home

  def home
    # # /menus/_menu.html.erb
    @menus = Menu.page(params[:page]).per(30)

    @user = current_user if logged_in?
  end

  private

    def delete_menu_sessions
      session[:menu_date].clear unless session[:menu_date].nil?
      session[:menu_time].clear unless session[:menu_date].nil?
    end
end

app/views/static_pages/_home_link.html.erb
<%= link_to link, data: {turbolinks: turbolinks} do %>
  <div class="home-link">
    <%= image_pack_tag(image) %>
    <div><%= title %></div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
  <aside class="top">
    <div class="home-title center jumbotron">
      <h1>日々の献立を管理しよう！</h1>
      <% if @user %>
        <%= profile_image(@user) %>
        <h5>こんにちは、<%= @user.name %>さん</h5>
      <% end %>

      <% if logged_in? %>
        <div class="home-grid">
          <%= render partial: 'home_link', locals: { link: user_path(@user),
              turbolinks: false, image: "my_menu.png", title: "私の献立"} %>

          <%= render partial: 'home_link', locals: { link: menus_path,
              turbolinks: false, image: "everyone's_menu.png", title: "みんなの献立"} %>

          <%= render partial: 'home_link', locals: { link: recommend_path,
              turbolinks: false, image: "recommended_menu.png", title: "ご無沙汰献立"} %>
        </div>
        <div class="home-grid">
          <%= link_to new_menu_path, remote: true do %>
            <div class="home-link">
              <%= image_pack_tag("register_menu.png") %>
              <div>献立の登録</div>
            </div>
          <% end %>

          <%= render partial: 'home_link', locals: { link: users_path,
              turbolinks: true, image: "friend_search.png", title: "友達検索"} %>

          <% unless @user == User.find_by(email: "test@railstutorial.org") %>
            <%= render partial: 'home_link', locals: { link: edit_user_path(@user),
                turbolinks: false, image: "my_page.png", title: "ユーザー編集"} %>
          <% end %>
        </div>
        <!-- </div> -->
      <% else %>
        <%= link_to "ユーザー登録", signup_path, class: "btn btn-lg btn-primary" %>
        <%= form_for(:session, url: login_path) do |f| %>
          <%= f.hidden_field :email, value: 'test@railstutorial.org' %>
          <%= f.hidden_field :password, value: 'foobar' %>
          <%= f.submit 'テストログイン', class: 'btn btn-lg btn-secondary' %>
        <% end %>
      <% end %>
    </div>
  </aside>

  <div class="home-section">
    <h2>みんなの献立</h2>
    <ol class="horizontal-list">
      <%= render @menus %>
    </ol>
  </div>

  <div class="home-section">
    <h2>機能紹介</h2>
    <div class="intro-item">
      <div class="intro-sentence">
        <div class="intro-title">
          ①献立カレンダー
        </div>
        <div class="intro-text">
          登録した献立をカレンダー形式で閲覧できる！
        </div>
      </div>
      <%= image_pack_tag("menu_calendar.png", class: "intro-img") %>
    </div>
    <div class="intro-item">
      <div class="intro-sentence">
        <div class="intro-title">
          ②みんなの献立
        </div>
        <div class="intro-text">
          他のユーザーが登録した献立が見れる！
        </div>
      </div>
      <%= image_tag("https://datesanimageserver.s3-ap-northeast-1.amazonaws.com/uploads/free/everyone's_menus.png", class: "intro-img") %>
    </div>
    <div class="intro-item">
      <div class="intro-sentence">
        <div class="intro-title">
          ③ご無沙汰献立
        </div>
        <div class="intro-text">
          登録した献立から最近食べていないものがわかる！
        </div>
      </div>
      <%= image_pack_tag("recommend_menus.png", class: "intro-img") %>
    </div>
  </div>

  <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
</div>