config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/recommend', to: 'recommended_menus#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :dishes, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_many :dishes, dependent: :destroy
  default_scope -> { order( date: :desc, time: :asc ) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :date, presence: true
  validates :time, presence: true, uniqueness: { scope: [:user_id, :date], case_sensitive: true }
  # case_sensitive: true ... 大文字小文字を区別するユニーク制約。これがないとrspecでエラーになる。明示せよと言われる。
  validate :picture_size

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 7.megabytes
        errors.add(:picture, "7MB以上の画像はアップロードできません。")
      end
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :index]
  before_action :set_menu_times, only: [:new, :create, :edit, :update]
  before_action :set_dish_categories, only: [:new, :create, :edit, :update]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :prepare_menu_form, only: [:new, :create, :edit, :update]

  def new
    if params[:menu]
      @menu = Menu.find(params[:menu])
    else
      @menu = current_user.menus.build(date: Date.today)
    end
    @dishes = []
    @dish_categories.each do |dish_category|
      dish = @menu.dishes.build(name: "", category: dish_category[0])
      @dishes << dish
    end
  end

  def create
    menu_find = Menu.find_by(date: menu_params[:date], time: menu_params[:time], user: current_user)
    @menu = menu_find || current_user.menus.build(date: menu_params[:date], time: menu_params[:time])
    @menu.assign_attributes(picture: menu_params[:picture]) if menu_params[:picture]
    if @menu.valid?
      @menu.save
    else
      render :error and return
    end

    dishes_attributes = menu_params[:dishes_attributes]
    dishes = dishes_build(@menu, dishes_attributes)

    # dishesにvalidationエラーがあった場合
    if dishes == false
      @menu.destroy unless menu_find
      render :error
    # 新しい献立で、品目の入力が無く、画像のみ入力があった場合
    elsif dishes.empty? && menu_params[:picture] && !menu_find
      @menu.destroy
      flash[:danger] = "新しい日付・時間帯の献立です。画像だけでは登録できません。品目を入力してください。"
      redirect_to user_path(current_user, start_date: @menu.date)
    # 既存献立への追加で、品目も画像ものみ入力が無かった場合
    elsif dishes.empty? && menu_params[:picture].nil?
      flash[:danger] = "品目や画像の入力がありませんでした。"
      @menu.destroy unless menu_find
      redirect_to user_path(current_user, start_date: @menu.date)
    # その他、登録成功
    else
      @menu.save
      dishes.each do |dish|
        dish.save
      end
      if menu_find
        flash[:success] = "献立が編集されました。"
      else
        flash[:success] = "献立を作成しました。"
      end
      redirect_to user_path(current_user, start_date: @menu.date)
    end
  end

  def destroy
    @menu.destroy
    flash[:success] = "献立を削除しました。"
    redirect_to request.referrer || root_url
  end

  def edit
    @menu = Menu.find(params[:id])
    @dishes = @menu.dishes.all
  end

  def update
    @menu = Menu.find(params[:id])
    if params[:delete_image] == "✖️" #画像削除ボタンが押されたら
      @menu.picture = nil
      @menu.save!
      flash[:success] = "献立の画像を削除しました。"
      redirect_to user_path(current_user, start_date: @menu.date)
    elsif @menu.update(date: menu_params[:date], time: menu_params[:time])
      @menu.update(picture: menu_params[:picture]) if menu_params[:picture]
      unless menu_params[:dishes_attributes] == ""
        menu_params[:dishes_attributes].keys.each do |dish_id|
          @dish = Dish.find(dish_id)
          @dish.assign_attributes({ name: menu_params[:dishes_attributes][dish_id][:name],
                                  category: menu_params[:dishes_attributes][dish_id][:category] })
          unless @dish.save
            render :error and return
          end
        end
      end
      flash[:success] = "献立が編集されました。"
      redirect_to user_path(current_user, start_date: @menu.date)
    else
      render :error
    end
  end

  def index
    @menus = Menu.page(params[:page]).per(30)

    @followings_menus = Menu.where(user: current_user.following)
    @followings_menus = Kaminari.paginate_array(@followings_menus).page(params[:page]).per(30)
  end

  private
    def menu_params
      params.require(:menu).permit(
        :date,
        :time,
        :picture,
        dishes_attributes: [
          :name,
          :category
        ]
      )
    end

    def correct_user
      @menu = current_user.menus.find_by(id: params[:id])
      redirect_to root_url if @menu.nil?
    end

    def dishes_build(menu, dishes)
      dishes_build = []
      dishes.each do |dish_params|
        unless dish_params[:name] == ""
          @dish = menu.dishes.build(dish_params)
          if @dish.valid?
            dishes_build << @dish
          else
            return false
          end
        end
      end
      return dishes_build
    end
end

app/helpers/menus_helper.rb
module MenusHelper

  def menu_image(menu, id)
    if menu.picture.url
      image_tag(menu.picture.url, id: id)
    else
      image_pack_tag("no_image.png", id: id)
    end
  end
end

app/views/menus/_followings_menus.html.erb
<% @followings_menus.each do |menu| %>
  <%= render 'menu', menu: menu %>
<% end %>
<%= paginate @followings_menus, remote: true %>

app/views/menus/_menu.html.erb
<% menu.picture.url.nil? ? @image_url = "../assets/no_image.png" : @image_url = menu.picture.url %>

<li class="everyone-menu-item">

  <div class="everyone-menu-picture">
    <%= menu_image(menu, "") %>

    <!-- .holizontal-listでのみ表示 -->
    <div class="datetime">
      <span><%= menu.date %></span>
      <span><%= menu.time %></span>
    </div>

    <div class="user">
      <%= menu.user.name %>
    </div>
    <!-- ここまで -->
  </div>

  <div class="everyone-menu-info">
    <!-- .vertical-listでのみ表示１ -->
    <span class="user"><%= link_to menu.user.name, user_path(menu.user) %></span>
    <!-- ここまで -->
    <ul class="dishes">
      <% menu.dishes.all.each do |dish| %>
        <li class="dish"><%= dish.name %></li>
      <% end %>
    </ul>
    <!-- .vertical-listでのみ表示２ -->
    <span class="datetime"><%= menu.date %> <%= menu.time %></span>
    <!-- ここまで -->
  </div>
</li>

app/views/menus/_menu_calendar.html.erb
<%= javascript_pack_tag 'menu_calendar', 'data-turbolinks-track': 'reload' %>

<div class="calendar">
  <% for num in -7..7 do %>
    <div class="calendar-header" id="num-<%= num %>" data-toggle="modal" data-target="#calendarModal">
      <%= @date+num %>
      <%= %w(日 月 火 水 木 金 土)[(@date+num).wday] %>
    </div>
    <% @menu_times.each do |time| %>
      <% if @menu = Menu.find_by(date: @date+num, time: time[0], user: current_user) %>
        <%= link_to(edit_menu_path(@menu), remote: true, class: "menu",
                                      id: "menu-#{@date+num}-#{time[0]}") do %>
          <div class="dishes">
            <% @menu.dishes.all.each do |dish| %>
              <li class="dish"><%= dish.name %></li>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="menu" id="menu-<%= @date+num %>-<%= time[0] %>"></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/menus/edit.html.erb
<% provide(:modal_header, "献立の編集") %>

<div class="row">
  <%= render 'shared/form' %>
</div>

app/views/menus/edit.js.erb
<% provide(:modal_header, "献立の編集") %>

$("#user-modal").html("<%= escape_javascript(render 'shared/menu_form') %>");
$("#user-modal").modal("show");

$('#menu_picture').on('click', function() {
  $('#preview').addClass("non-active");
  $('#form-menu-img').removeClass("non-active");
  $('#delete-image').removeClass("non-active");
  $('#message-with-picture').addClass("non-active");
});

$('#menu_picture').on('change', function() {
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 7) {
    alert('最大ファイルサイズは7MBです。');
  }

  $('#form-menu-img').addClass("non-active");
  $('#delete-image').addClass("non-active");
  $('#preview').removeClass("non-active");
  var file = $(this).prop('files')[0];
  var reader = new FileReader();
  reader.onload = function(e) {
    $('#preview').attr('src', e.target.result);
  }
  reader.readAsDataURL(file);
  $('#message-with-picture').removeClass("non-active");
  $('#message-with-picture').addClass("active");
});

app/views/menus/error.js.erb
$('.menu-error-message').text("<%= @menu.errors.full_messages.join(",").html_safe if @menu %>");
$('.dish-error-message').text("<%= @dish.errors.full_messages.join(",").html_safe if @dish %>");

app/views/menus/index.html.erb
<%= javascript_pack_tag 'menus_index', 'data-turbolinks-track': 'reload' %>

<% provide(:title, "みんなの献立") %>

<div class="row">
  <div class="col-md-12">
    <h1>みんなの献立</h1>
    <ul class="tab">
      <li id="tab1" class="active">全てのユーザー</li>
      <li id="tab2">フォロー中</li>
    </ul>
    <div class="tab_cnt">
      <div id="tab1_cnt" class="active">
        <ol class="vertical-list" id="all-menu">
          <%= render @menus %>
          <%= paginate @menus %>
        </ol>
      </div>
      <div id="tab2_cnt">
        <ol class="vertical-list" id="followings_menus">
          <%= render 'followings_menus' %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/menus/index.js.erb
$('#followings_menus').html("<%= escape_javascript(render 'followings_menus') %>");

app/views/menus/new.html.erb
<% provide(:modal_header, "新しい献立を登録しましょう。") %>

<div class="row">
  <%= render 'shared/menu_form' %>
</div>

app/views/menus/new.js.erb
<% provide(:modal_header, "新しい献立を登録しましょう。") %>

$("#user-modal").html("<%= escape_javascript(render 'shared/menu_form') %>");
$("#user-modal").modal("show");

$('#menu_picture').on('click', function() {
  $('#preview').addClass("non-active");
  $('#form-menu-img').removeClass("non-active");
  $('#message-with-picture').removeClass("active");
  $('#message-with-picture').addClass("non-active");
});

$('#menu_picture').on('change', function() {
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 7) {
    alert('最大ファイルサイズは7MBです。');
  }

  $('#form-menu-img').addClass("non-active");
  $('#preview').removeClass("non-active");
  var file = $(this).prop('files')[0];
  var reader = new FileReader();
  reader.onload = function(e) {
    $('#preview').attr('src', e.target.result);
  }
  reader.readAsDataURL(file);
  $('#message-with-picture').removeClass("non-active");
  $('#message-with-picture').addClass("active");
});

app/views/menus/success.js.erb
$('input[type="text"]').val('');
$('#user-modal').modal('hide')

location.href = <% user_url(@user, start_date: @menu.date) %>;