config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/recommend', to: 'recommended_menus#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :dishes, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :menus, dependent: :destroy
  has_many :dishes, through: :menus
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :picture, PictureUploader

  scope :search, -> (search_params) do
    name_is(search_params[:name])
  end

  scope :admin_search, -> (search_params) do
    name_like(search_params[:name])
  end

  scope :name_is, -> (name) { where(name: name) }
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                    reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :show,
                                        :following, :followers]
  before_action :correct_user, only: [:edit, :update, :following, :followers]
  before_action :correct_or_admin_user, only: :destroy
  before_action :set_menu_times, only: :show
  before_action :set_dish_categories, only: :show
  before_action :logged_in_testuser, only: [:edit, :update]

  def index
    @search_params = user_search_params
    if current_user.admin?
      @users = User.where(activated: true)
                  .where.not(id: current_user.id).admin_search(@search_params)
    else
      @users = User.where(activated: true)
                  .where.not(id: current_user.id).search(@search_params)
    end

    if @users
      @users = Kaminari.paginate_array(@users).page(params[:page]).per(30)
    else
      flash[:danger] = "一致するユーザーがいませんでした。
                        入力したユーザー名と完全に一致するユーザーのみを表示します。"
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?

    # menus/menu_calendar
    params[:start_date] ? @date = params[:start_date].to_date : @date = Date.today
    @menus = @user.menus.all
    @menus = Kaminari.paginate_array(@menus).page(params[:page]).per(30)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "メールを確認して、アカウントを有効にしてください。"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.admin?
      flash[:danger] = "管理者は削除できません。"
      redirect_to root_path
    else
      @user.destroy
      if current_user.admin?
        flash[:success] = "ユーザーを削除しました。"
        redirect_to users_path
      else
        flash[:success] = "ご利用ありがとうございました。"
        redirect_to root_path
      end
    end
  end

  def following
    @title = "フォロー"
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation, :picture)
    end

    def user_search_params
      params.fetch(:search, {}).permit(:name)
    end

    # beforeアクション

    # ユーザーが本人かどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # ユーザーが本人または管理者かどうか確認
    def correct_or_admin_user
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        redirect_to(root_url)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar avatar")
  end

  def profile_image(user)
    if user.picture.url
      image_tag(user.picture.url, class: "avatar")
    else
      gravatar_for(user)
    end
  end

  def events_ajax_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
  end

  def events_ajax_next_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  end
end

app/views/users/_calendar.html.erb
<%= month_calendar previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date| %>
  <div class="week-color"><%= link_to "#{date.day}", user_path(@user, start_date: date) %></div>

  <% Menu.where(date: date, user: @user).sort{|a, b| a["time"]<=>b["time"]}.reverse.each do |menu| %>
    <div class="day-content" id="<%= menu.time %>"><%= menu.time[0, 1] %></div>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <div class="col-xs-12">
    <%= f.label :name, "ユーザー名" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "パスワード（再確認）" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary btn-users-form" %>
  </div>
<% end %>

app/views/users/_search_error.html.erb
<div id="error-user-search">
  <p>検索したユーザー名はありませんでした。</p>
  <p>ユーザー名が完全に一致したユーザーのみが検索されます。</p>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-success" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= profile_image user %>
  <%= link_to user.name, user %>
  <%= render 'stats' if current_user?(user) %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= render partial: 'delete_user', locals: { user: user } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<% provide(:button_text, "保存") %>
<% provide(:delete_text, "こちら") %>

<h1>ユーザー編集</h1>
<div class="row">
  <div class="col-xs-12">
    <div class="avatar-edit">
      <%= profile_image(@user) %>

      <%= form_with(model: @user, remote: true, id: "avatar_edit", method: :patch) do |f| %>
        <%= f.label :picture, "画像", class: "btn image_input_btn" %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "user_picture" %>
      <% end %>
    </div>

    <%= render 'form' %>
    <div class="delete-link">
      お使いのユーザーの削除は
      <%= render partial: 'delete_user', locals: { user: @user } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー検索") %>
<% provide(:url, users_path) %>
<% provide(:placeholder, "ユーザー名を入力") %>
<% provide(:submit, "検索") %>
<% provide(:search_word, "") %>
<%= provide(:delete_text, "delete") %>

<section class="users user_info">
  <%= render partial: 'user_info', locals: { user: current_user } %>
  <%= render 'stats' %>
</section>

<%= render 'shared/search_form' %>

<section class="users" id="search-results">
  <%= render @users %>
</section>

<%= paginate @users %>

app/views/users/index.js.erb
<% unless @users.empty? %>
  $("#search-results").html("<%= escape_javascript(render @users) %>");
<% else %>
  $("#search-results").html("<%= escape_javascript(render 'search_error') %>");
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー登録') %>
<% provide(:button_text, '登録') %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:url, dishes_path) %>
<% provide(:placeholder, "検索する品名を入力") %>
<% provide(:submit, "献立検索") %>

<% if current_user?(@user) %>
  <% provide(:search_word, "") %>
  <%= render 'shared/search_form' %>
  <%= render 'menus/menu_calendar' %>
  <div class="button-area">
    <div class="round-button" id="calendar-button" data-toggle="modal" data-target="#calendarModal">
      <%= image_pack_tag("calendar.png") %>
    </div>
    <div class="round-button">
      <%= link_to image_pack_tag("register_menu.png"), new_menu_path, remote: true %>
    </div>
  </div>
<% else %>
  <section class="users user_info">
    <%= render partial: 'user_info', locals: { user: @user } %>
    <%= render 'follow_form' if logged_in? %>
  </section>
  <ol class="vertical-list">
    <%= render @menus %>
    <%= paginate @menus %>
  </ol>
<% end %>
<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

  <!-- ボタン・リンククリック後に表示される画面の内容 -->
<div class="modal fade" id="calendarModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <%= render 'shared/modal_calendar' %>
</div>

app/views/users/show.js.erb
$("#events_calendar").html("<%= escape_javascript render(partial: "calendar") %>");

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<section class="users user_info">
  <%= render partial: 'user_info', locals: { user: current_user } %>
</section>

<h1><%= @title %></h1>
<% if @users.any? %>
  <ul class="users follow">
    <%= render @users %>
  </ul>
  <%= paginate @users %>
<% end %>